install.yaml

* #13 
It turns out that services.yml/.platform.app can use any random value for the db section; it has to be derived from the arbitrary value used in .platform.app. See #13

Allow arbitrary database type derived from .platform.app, fixes #13

---

homeadditions/.bashrc.d/platformsh-environment.sh
install.yaml

First work on trying to populate environment variables, including PLATFORM_ROUTES
Unfortunately, I'm probably stuck. Will need to do a collaborative debugging session to understand this I think.

Populate environment variables as needed, fixes #15, fixes #16

---

README.md
install.yaml

* #23 
* #11 
* #8 
Although each of these can be a little fragile, they're all handled here.
This requires composer global installs to go into a new COMPOSER_HOME, which is not normally there with DDEV. Maybe it should be.

Support PHP extensions, Python3 packages, and global composer requirements, fixes #23, fixes #11, fixes #8

---

install.yaml

* #24
pointed out a behavior introduced late in DDEV v1.20.0, where `ddev get` forced ddev to start, creating a database (of the wrong type).
That behavior has been rolled back, and new features that check database type, etc. have been introduced.
Hopefully this will solve #24.
This also works on a number of advanced issues found in #24:
* The build, deploy, post_deploy hooks are now translated as a multiline script, the same as they are in the .platform.app.yaml, which makes lots of things work better than they otherwise could.
* Some PHP extension packages get special handling

Use ddev debug get-volume-db-version to get existing volume, for #24

---

install.yaml
web-build/Dockerfile.platformsh

* #31 
In the Dockerfile, the `platform self:update` would be cached, no perhaps never updated. Move to post-start hook.

Always self:update platform tool if possible, fixes #31

---

install.yaml

* #39 
The Platform token was going into the project config, but it's better for it to be in global config.

Put Platform token in global config where it won't get committed, fixes #39

---

install.yaml

This also takes care of adding the proper information to ~/.ssh/config.

Generate key-less SSH certificate on start

---

install.yaml

* #38 
It turned out this was not actually a failure in the relationship mapping, but a failure of transformation of `mysql` to `mariadb`
This PR fixes the failure that happened with blog.blackfire.io.

Fix munging of mysql/mariadb/oracle-mysql db types, fixes #38

---

install.yaml

I was using this line and found two issues:
- exec is run with set +u so if the env var is not there it fails, now it wont
- and also, if the test of the token (without the above error) is false, it also provides an error exit code, so added `|| true` in the end as well.

Fix potential errors when trying to cert:load

---

install.yaml
tests/wordpress-composer.bats

* #54 
* PLATFORM_RELATIONSHIPS was not being encoded correctly on Linux due to use of base64, which is different in the two places
What was actually happening is there was a misplaced {{end}}, and the result was that environment variables were enclosed in an `if runtime.extensions` block. And the wordpress-composer template doesn't have any runtime.extensions, so the entire environment section was being omitted. 
Also added a bit to the wordpress-composer test, to at least check for PLATFORM_RELATIONSHIPS.
This can be tested with `ddev get https://github.com/rfay/ddev-platformsh/tarball/20221108_fix_wp`

Environment output was inside section only intended for runtime.extensions, fixes #54

---

install.yaml
platformsh/.gitignore

Improve output from `ddev get platformsh/ddev-platformsh` by adding `#ddev-description` lines. 
See 
* https://github.com/drud/ddev/pull/4414

Add #ddev-description for descriptive output during installation

---

tests/wordpress-composer.bats

Tests broke because wordpress-composer template now does php 8.1

Update wordpress-composer test; now php 8.1

---

homeadditions/.bashrc.d/platformsh-environment.sh
install.yaml

`/var/www/html/.global/bin` was not correctly set in the `$PATH` using regular `web_environment` section.
Fix #74

PATH addition not working, add it in platform-environment.sh

---

install.yaml
tests/drupal9.bats

* #47 
This PR just
* Changes to expand PLATFORM_ROUTES (a single element) correctly
* Adds a test to make sure that happens
This may not be enough for #47 - please let me know if we need to go beyond having a fixed single route at this time.
test:
```
ddev get https://github.com/rfay/ddev-platformsh/tarball/20221208_platform_routes
ddev restart
ddev exec 'echo $PLATFORM_ROUTES | base64 -d | jq'
```

PLATFORM_ROUTES should properly expand the primary URL, fixes #47

---

install.yaml

* #46 
Current known local-install tools are base64, jq, perl;; this checks for them and warns that they're needed. 
We'd like to get rid of external dependencies, but this will do for now. 
* https://github.com/drud/ddev/pull/4441 also improves this experience, by not showing a whole wall of text by default when a step fails.

Add a step to check for required tools, fixes #46

---

README.md

Closes #82 
Adds a list of [Platform-provided environmental variables](https://docs.platform.sh/development/variables/use-variables.html#use-platformsh-provided-variables) that are currently supported in DDEV.
List of variables that are "missing" or not yet implemented:
* PLATFORM_APPLICATION
* PLATFORM_BRANCH
* PLATFORM_DOCUMENT_ROOT
* PLATFORM_ENVIRONMENT_TYPE
* PLATFORM_OUTPUT_DIR
* PLATFORM_SMTP_HOST
* PLATFORM_SOURCE_DIR
* PORT - not always available 
* SOCKET
There are two `PLATFORM_*` environmental variables in DDEV that do not map to ones we provide. 
* PLATFORM_DIR - is this possibly supposed to be `PLATFORM_DOCUMENT_ROOT` that is "missing"?
* PLATFORM_MOUNTS

Supported Platform.sh provided environmental vars, fixes #82

---

install.yaml

* drud/ddev#4539
It turns out this can be fixed easily in this add-on; we just don't need to be telling them what we're doing in the earlier stanza.

Don't confuse issue with output before prompt, fixes drud/ddev#4539

---

README.md
install.yaml

* #100
* #96
* #46
* #93
We've been very fragile with regard to requiring the user to install
* base64
* jq
* perl
* sed
* shasum
This switches to using a lightweight docker image to do those activities.

Use a lightweight docker image to replace fragile jq, shasum, etc, fixes #100, for #46, fixes #96, fixes #93

---

.github/workflows/tests.yml

The keepalive workflow pushes a commit; if it runs on both workflows it breaks.
Only run it on "stable"

[tests only] keepalive workflow only runs on stable, prevent conflict

---

.github/workflows/tests.yml
README.md

* Much of the tests.yaml can now be removed in favor of https://github.com/ddev/github-action-add-on-test

ci: maintenance on tests to use new github action

---

install.yaml
tests/composerversion.bats
tests/testdata/composerversion/composer_2.5.6/.platform.app.yaml
tests/testdata/composerversion/composer_^1/.platform.app.yaml
tests/testdata/composerversion/composer_^2/.platform.app.yaml

We need to use the composer version found in .platform.app.yaml
Attempts to parse the composer/composer php dependency if it exists, and translate it into ddev's format, `composer_version: "2"` for example.
This can be tested using
```
ddev get rfay/ddev-platformsh/tarball/20230829_composer_version
```
Added composerversion test

feat: support composer version when found in .platform.app.yaml

---

README.md
install.yaml

* #116
There are project types other than php - and we don't support them at this time.
* Error out with a message if trying to use non-php project type.
* State clearly in README that only PHP is supported.
See #116
Test with `ddev get https://github.com/rfay/ddev-platformsh/tarball/20230905_python_project`

fix: check to make sure project type is php before continuing, fixes #116

---

.github/workflows/tests.yml
tests/composerversion.bats
tests/drupal10.bats
tests/drupal9.bats
tests/laravel.bats
tests/mysql.bats
tests/oddrelationships.bats
tests/oracle-mysql.bats
tests/php.bats
tests/postgresql.bats
tests/wordpress-bedrock.bats
tests/wordpress-composer.bats

Recent tests on HEAD have been showing this output on every single command (like all `ddev exec`) and it breaks some fragile comparisons.
> Instrumentation is opted in, but AmplitudeAPIKey is not available. This usually means you have a locally-built ddev binary or one from a PR build. It's not an error. Please report it if you're using an official release build.
* Direct stderr to /dev/null on ddev exec, which cleans it up
It looks to me like `brew install --HEAD` version of ddev/ddev/ddev is showing this on all commands, but that's a bit much. It could only show on `ddev start`. I think this is a recent regression in ddev or homebrew.

remove extraneous output from ddev head version

---

tests/composerversion.bats

In composer version 2.7.2 they changed the output of composer --version; broke test
Improve the test to handle it.

tests: composerversion test failed due to composer version output changing

---

install.yaml

* #122 
`self:update` was removed in the go version of `platform` cli.
Don't do it any more.

Remove obsolete platform self:update, fixes #122

---

.github/workflows/tests.yml

This PR bumps github-action-add-on to v2.
This prevents the dummy commits created by the keep-alive action.
See https://github.com/ddev/github-action-add-on-test/releases/tag/v2.0.0

bump github-action-add-on

---

README.md
install.yaml

* We can now use `ddev_version_constraint` instead of using the `ddev debug capabilities` we used in the past.
* `ddev_version_constraint` is now v1.23.3.
* Update README with a couple of normal updates.

update README and install.yaml, use newer techniques

---

.github/workflows/tests.yml
README.md
install.yaml

Upstream `ddev-addon-template` has some changes.
- Uses v1.24.3 version constraint
- Adds new badges to the README.md
- Updates tests.yml concurrency
```bash
ddev add-on get https://github.com/ddev/ddev-platformsh/tarball/20250418_stasadev_readme_and_constraint
ddev restart
```

refactor: use v1.24.3 constraint, update readme, concurrency in test

---

tests/drupal11.bats

The upstream template changed to use mariadb:10.11 from 10.6 in 
* https://github.com/platformsh-templates/drupal11/pull/7
Look for 10.11 now.

test: Update drupal11 test to use mariadb:10.11
